services:
  # Postgres master node
  postgres-master:
    image: postgres:16
    container_name: postgres-master
    environment:
      POSTGRES_PASSWORD: masterpass
    volumes:
      - master-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sdhl-network
  # Postgres slave nodes
  postgres-slave1:
    image: postgres:16
    container_name: postgres-slave1
    environment:
      POSTGRES_PASSWORD: slavepass
    volumes:
      - slave1-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - postgres-master
    networks:
      - sdhl-network

  postgres-slave2:
    image: postgres:16
    container_name: postgres-slave2
    environment:
      POSTGRES_PASSWORD: slavepass
    volumes:
      - slave2-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    depends_on:
      - postgres-master
    networks:
      - sdhl-network

  # HAProxy to connect master and slaves nodes of pg instances
  haproxy:
    image: haproxy:2.9
    container_name: web-haproxy
    ports:
      - "5435:5432"
      - "5436:5433"
    volumes:
      - ./etc/haproxy/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - postgres-master
      - postgres-slave1
      - postgres-slave2
    networks:
      - sdhl-network

  # Nginx to load balance between three backend instances
  nginx:
    image: nginx:latest
    container_name: web-nginx
    ports:
      - "8080:80"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-1
      - backend-2
      - backend-3
    networks:
      - sdhl-network

  # Backend instances
  backend-1:
    image: golang:1.23.4-alpine
    container_name: web1
    working_dir: /app
    volumes:
      - ./backend:/app
    command: go run main.go
    expose:
      - "8081"
    depends_on:
      - postgres-master
      - postgres-slave1
      - postgres-slave2
    networks:
      - sdhl-network

  backend-2:
    image: golang:1.23.4-alpine
    container_name: web2
    working_dir: /app
    volumes:
      - ./backend:/app
    command: go run main.go
    expose:
      - "8081"
    depends_on:
      - postgres-master
      - postgres-slave1
      - postgres-slave2
    networks:
      - sdhl-network

  backend-3:
    image: golang:1.23.4-alpine
    container_name: web3
    working_dir: /app
    volumes:
      - ./backend:/app
    command: go run main.go
    expose:
      - "8081"
    depends_on:
      - postgres-master
      - postgres-slave1
      - postgres-slave2
    networks:
      - sdhl-network

volumes:
  master-data:
  slave1-data:
  slave2-data:

networks:
  sdhl-network:
    driver: bridge
